// <auto-generated />
using LoginService.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace LoginService.Migrations.LoanDetail
{
    [DbContext(typeof(LoanDetailContext))]
    [Migration("20200823180458_LoanDbMigration")]
    partial class LoanDbMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("LoginService.Models.LoanDetail", b =>
                {
                    b.Property<int>("LNId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("LegalDocuments")
                        .IsRequired()
                        .HasColumnType("varchar(15)");

                    b.Property<string>("LoanAmount")
                        .IsRequired()
                        .HasColumnType("varchar(5)");

                    b.Property<string>("LoanNumber")
                        .IsRequired()
                        .HasColumnType("varchar(5)");

                    b.Property<string>("LoanOwnerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LoanTerm")
                        .IsRequired()
                        .HasColumnType("varchar(2)");

                    b.Property<string>("LoanType")
                        .IsRequired()
                        .HasColumnType("varchar(5)");

                    b.HasKey("LNId");

                    b.ToTable("LoanDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
